### PR TITLE
Fix/ngocnt

### PR DESCRIPTION
**Pull request by blackmouse572**
[[QLN-305] fix: shuffle random flashcard not loading]
[QLN-312] fix: cannot filter quizbank

[QLN-305]: https://cyphered.atlassian.net/browse/QLN-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[QLN-312]: https://cyphered.atlassian.net/browse/QLN-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pikaden** [comment]
This bug only appear after shuffle flashcard
bug:
image
This quizbank is 20 flashcard, but it only slide to quizbank 10
quizbank id: http://localhost:3000/quizbank/31

This bug is appear in the page
bug:
the flip button key binding now is arrow down and up, but it is affect the scroll bar. 
Suggestion: prevent default of the browser?

**Comment by pikaden** [comment]
bug:
when first time access to quizbank page, press r or click toggle random, the flashcard will not shuffle random, must click or press r for again some time to toggle random

**Comment by blackmouse572** [comment]
> bug: when first time access to quizbank page, press r or click toggle random, the flashcard will not shuffle random, must click or press r for again some time to toggle random

This require time to load so no fix

**Review by pikaden — APPROVED** [review]
OK good effort!

**Pull request merged**
